site_name: UFDL API
site_url: https://github.com/waikato-datamining/ufdl-api
site_description: API documentation for the user-friendly deep-learning (UFDL) framework.
theme:
    name: readthedocs
nav:
  - 'Home': index.md
  - 'User management': user_management.md
  - 'Job execution': jobs.md
  - 'Application domains':
    - 'Object Detection': object_detection.md

