site_name: UFDL API
site_url: https://github.com/waikato-datamining/ufdl-api
site_description: API documentation for the user-friendly deep-learning (UFDL) framework.
theme:
    name: readthedocs
nav:
  - 'Home': index.md
  - 'Core':
    - 'Authentication': authentication.md
    - 'CUDA': cuda.md
    - 'Docker images': docker_images.md
    - 'Domains': domains.md
    - 'Frameworks': frameworks.md
    - 'Hardware': hardware.md
    - 'Licenses': licenses.md
    - 'Nodes': nodes.md
    - 'Pretrained models': pretrained_models.md
    - 'Projects': projects.md
    - 'Teams': teams.md
    - 'Users': users.md
  - 'Job execution':
    - 'Jobs': jobs.md
    - 'Job templates': job_templates.md
  - 'Data':
    - 'Core dataset': datasets.md
    - 'Image classification': image_classification.md
    - 'Object Detection': object_detection.md
    - 'Speech': speech.md
  - 'Filtering': filtering.md
