site_name: UFDL API
site_url: https://ufdl.cms.waikato.ac.nz/ufdl-api/
site_description: API documentation for the user-friendly deep-learning (UFDL) framework.
repo_url: https://github.com/waikato-ufdl/ufdl-api
edit_uri: edit/master/docs/
theme:
    name: material
markdown_extensions:
    - toc:
        baselevel: 2
        permalink: "#"
plugins:
    - search
nav:
  - 'Home': index.md
  - 'Core':
    - 'Authentication': authentication.md
    - 'CUDA': cuda.md
    - 'Docker images': docker_images.md
    - 'Domains': domains.md
    - 'Frameworks': frameworks.md
    - 'Hardware': hardware.md
    - 'Licenses': licenses.md
    - 'Nodes': nodes.md
    - 'Pretrained models': pretrained_models.md
    - 'Projects': projects.md
    - 'Teams': teams.md
    - 'Users': users.md
  - 'Job execution':
    - 'Jobs': jobs.md
    - 'Job templates': job_templates.md
    - 'Job outputs': job_outputs.md
    - 'Job types': job_types.md
  - 'Data':
    - 'Core dataset': datasets.md
    - 'Image classification': image_classification.md
    - 'Image segmentation': image_segmentation.md
    - 'Object Detection': object_detection.md
    - 'Speech': speech.md
  - 'Filtering': filtering.md
  - 'Permissions': permissions.md
