site_name: UFDL API
site_url: https://github.com/waikato-datamining/ufdl-api
site_description: API documentation for the user-friendly deep-learning (UFDL) framework.
theme:
    name: readthedocs
nav:
  - 'Home': index.md
  - 'User management': user_management.md
  - 'Data storage': data_storage.md
  - 'Docker images': docker_images.md
  - 'CUDA': cuda.md
  - 'Hardware': hardware.md
  - 'Job execution': jobs.md
  - 'Data domains':
    - 'Image classification': image_classification.md
    - 'Object Detection': object_detection.md
    - 'Speech': speech.md
  - 'Model Zoo': model_zoo.md
  - 'Model templates': model_templates.md
  - 'Licenses': license_overview.md
